### ISSUE TITLE
v1.0.0 Goals

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#13]
**Goals, suggestions and ideas for the CIDRAM v1.0.0 version/release.**
_This list isn't static; Entries may be added and/or removed without notice._

_Code changes, features, etc._
- [x] [Added => v0.4.0] Add YAML-like support to signature files. _Refer #6_
- [x] [Added => v0.5.0] Implement reCAPTCHA solution to allow bypassing false positives.
- [x] [Added => v0.9.0] Completion of all items listed in the "front-end system to-do list" (#16).
- [x] Additional modules for improved security coverage.

_Documentation/L10N._
- [x] [Added => v0.5.0] Missing documentation: reCAPTCHA.
- [x] [Added => v0.5.1] Missing documentation: Expiry tags.
- [x] [Added => v0.5.1] Missing documentation: Using YAML in the signature files.
- [x] [Added => v0.5.1] Add "Frequently Asked Questions" section to the READMEs.
- [x] [Fixed => v0.5.1] `ignore.dat` is currently missing from the "files included in this package" list included in the documentation.
- [x] [Completed => v0.6.1] Targeted translations for internal language data.
- [x] [Completed => v0.7.1] Targeted translations for README documentation.
- [x] [Completed => v0.9.0] Planned supplementary translations for internal language data.
- [x] [Completed => v0.7.0] Planned supplementary translations for README documentation.
- [x] [Completed => v0.7.0] Missing documentation: "CONTRIBUTING.md" file.

_Bugs._
- [x] [Fixed => v0.4.0] Incorrect typecasting bug for configuration directives.

_Final changes (v0.9.0 > v1.0.0)._
- [x] [Resolved] "Compatibility with multiple vHosts/domains". #15
- [x] [Resolved] Expand themes, if possible.
- [x] New L10N/translations offered by some users. Not sure about progress. May arrive soon. A small delay period recommended prior to the final v1.0.0 release to accommodate the possibility of these being completed prior to the the final v1.0.0 release.

**Comment by Maikuolan** [comment]
*Resolved: Missing documentation: "CONTRIBUTING.md" file.*

**Comment by Maikuolan** [comment]
*Resolved: Targeted translations for README documentation.*

**Comment by Maikuolan** [comment]
*Resolved: Additional modules for improved security coverage.*

**Comment by Maikuolan** [comment]
*Resolved: Completion of all items listed in the "front-end system to-do list" (#16).*

**Comment by Maikuolan** [comment]
*Added "final changes" section to the list.*

**Comment by Maikuolan** [comment]
*Resolved: "Compatibility with multiple vHosts/domains" (#15).*

**Comment by Maikuolan** [comment]
Still hoping to get some more done between now and the eventual v1.0.0, but we've got at least 4 themes available at this point (albeit very simple themes, consisting of not much more than a change of colour scheme), so, marking *"Expand themes, if possible"* as resolved.

**Comment by Maikuolan** [comment]
*Marking issue as resolved and closing.*
