### ISSUE TITLE
Front-end system to-do list

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#16]
**Front-end system to-do list**
_An issue for tracking progress made towards the front-end system for CIDRAM. Items will be added as they become relevant and marked off upon completion._
- [x] Alpha stage: Coming up with some new plans, ideas, etc; Syncing some initial commits (getting the bare bones of the front-end system working).
- [x] Beta stage: Fleshing it out a bit more; Trying to implement some of our plans, ideas, etc (the front-end system mightn't be completed, but should be at least more functional by this stage; this item should only be marked as completed upon thorough testing of all changes to ensure that everything is working as intended).
- [x] Configuration update.
- [x] Documentation update.
- [x] Access/login/sessions system.
- [x] Build a front-end updates manager.
- [x] Build a front-end configuration manager.
- [x] Build a CIDR calculator.

**Comment by Maikuolan** [comment]
*v0.6.0 released. Front-end is basically now complete. Still pending items include the front-end installer, which hasn't yet been started, and the documentation, which may take a while to finish but remains on the to-do list. Issue will remain open until those items are completed.*

**Comment by Maikuolan** [comment]
*Completed: Build a CIDR calculator.*

**Comment by Maikuolan** [comment]
*Completed: Documentation update.*

**Comment by Maikuolan** [comment]
*Scratching installer off the to-do list and marking issue as implemented.*
