### ISSUE TITLE
v0.2.0 Goals

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#5]
**Goals, suggestions and ideas for the CIDRAM v0.2.0 version/release.**
_This list isn't static; Entries may be added and/or removed without notice._

_Code changes, features, etc._
- [x] Rename all `INC` files to `PHP` files and adjust all references accordingly. _Refer #3_
- [x] Bogon directive should be disabled by default.
- [x] Implement a "Why blocked" field for debugging, for logfiles and for users to better explain why users are blocked when they're blocked. _Refer #3_
- [x] Create fallback mechanism for when the specific `ipaddr` doesn't exist or is empty (such as for `REMOTE_ADDR`). _Refer #4_
- [x] Add support for multiple types of linebreaks (Windows/Unix/Linux/iOS/etc).
- [x] Add support for section tags.
- [x] Complete implementation of all section tags.
- [x] All comments should be hashed by default (not enforced on execution, but recommended by the validator). _Refer #3_
- [x] Rename custom signature files to avoid overwriting during blind updates.
- [x] Rename configuration file (`config.ini` -> `config.ini.RenameMe`) to avoid overwriting during blind updates.
- [x] Custom signature files and the configuration should all be optional (not mandatory).
- [x] Ability to display reconstructed URL to the user when they're blocked and add reconstructed URL to the logfiles.
- [x] Add support for multiple logfile formats.
- [x] Enhance flexibility for the output of custom error codes (options for 503, etc). _Refer #3_
- [x] Ability to use custom template files and custom CSS files for page output.
- [x] Complete CLI-mode implementation (i18n support, output defaults, directive to disable it, etc).
- [x] Add support for expiry tags.
- [x] Creation of an external validator/fixer. _Refer #3_

_Documentation._
- [x] Update all README documentation to include the information currently available within the custom signature files (such as regarding signature format and structure, etc). _Refer #3_

_Bugs._
- [x] [Fixed => v0.1.2] IPv6 CIDR generation bug. _Refer #2_
- [x] [Fixed => v0.2.0] Correct identification of PHP mode (CLI, CGI, Apache, etc) bug. _Refer #4_
- [x] [Fixed => v0.2.0] Whitelist signatures being ignored bug. _Refer #7_
